name: Go tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test: 
    strategy:
      matrix:
        go-version: [1.21.x]
        platform: [ubuntu-latest, windows-latest]
        build_tags: ["", "gtk_overlay"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
        
      - if: matrix.platform == 'ubuntu-latest'
        name: Install libayatana-appindicator3
        run: |
          sudo apt-get install libayatana-appindicator3-dev

      - name: Build
        run: go build -v -tags=${{matrix.build_tags}} ./...

      - name: Test
        run: go test -v -tags=${{matrix.build_tags}} ./...
