name: release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
        
      - name: Install dependencies
        run: |
          sudo apt-get install libayatana-appindicator3-dev

      - name: Install just
        uses: taiki-e/install-action@just
          
      - name: Build
        run: |
          version=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          just build_release_linux $version
          just build_release_windows $version
          just build_release_macos $version
          
      - name: Release 
        uses: softprops/action-gh-release@v1 
        with: 
          draft: false 
          prerelease: false 
          files: |
            ./dist/kanata-tray.exe
            ./dist/kanata-tray
            ./dist/kanata-tray-macos
            LICENSE